services:
  - type: web
    name: crypto-bot-v4
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        generateValue: true
    healthCheckPath: /status
    autoDeploy: true